import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { buildHomepageStaticHtml } from "../seo/homepageSeoContent.js";

test("Landing uses the product design shell without the old orb/glass hero", async () => {
  const landingSource = await readFile(new URL("./Landing.jsx", import.meta.url), "utf8");
  const cssSource = await readFile(new URL("../index.css", import.meta.url), "utf8");
  const seoSource = await readFile(new URL("../seo/homepageSeoContent.js", import.meta.url), "utf8");
  const sidebarSource = await readFile(new URL("../components/layout/Sidebar.jsx", import.meta.url), "utf8");
  const publicFooterSource = await readFile(new URL("../components/layout/PublicFooter.jsx", import.meta.url), "utf8");
  const indexSource = await readFile(new URL("../../index.html", import.meta.url), "utf8");
  const source = landingSource + cssSource + seoSource + sidebarSource + publicFooterSource + indexSource;
  const staticShell = buildHomepageStaticHtml();

  assert.match(source, /ResuMe by Ayush/);
  assert.match(source, /Ayuslh\.in/);
  assert.match(landingSource, /app-design/);
  assert.match(landingSource, /className="container" style=\{\{ display: "flex", alignItems: "center", height: 64, gap: 24 \}\}/);
  assert.match(landingSource, /position:\s*"sticky"/);
  assert.match(landingSource, /backdropFilter:\s*"blur\(12px\)"/);
  assert.match(landingSource, /color-mix\(in oklch, var\(--bg\) 78%, transparent\)/);
  assert.match(staticShell, /<header class="sticky top-0 z-30 border-b border-\[var\(--border\)\]"/);
  assert.match(staticShell, /backdrop-filter:blur\(12px\)/);
  assert.match(staticShell, /color-mix\(in oklch, var\(--bg\) 78%, transparent\)/);
  assert.match(landingSource, /paddingTop:\s*88/);
  assert.match(landingSource, /paddingBottom:\s*96/);
  assert.match(landingSource, /grid-template-columns:\s*1\.05fr \.95fr/);
  assert.match(landingSource, /gap:\s*56px/);
  assert.match(landingSource, /padding:\s*"20px 24px"/);
  assert.match(landingSource, /Trusted by candidates targeting roles at/);
  assert.match(landingSource, /landing-company-ticker/);
  assert.match(landingSource, /landing-company-track/);
  assert.match(landingSource, /landing-company-segment/);
  assert.match(landingSource, /paddingTop:\s*96,\s*paddingBottom:\s*64/);
  assert.match(landingSource, /marginBottom:\s*56/);
  assert.match(landingSource, /paddingTop:\s*32,\s*paddingBottom:\s*64/);
  assert.match(landingSource, /paddingTop:\s*64,\s*paddingBottom:\s*96/);
  assert.match(landingSource, /padding:\s*"56px 48px"/);
  assert.match(publicFooterSource, /padding:\s*"28px 24px"/);
  assert.match(staticShell, /style="padding-top:88px;padding-bottom:96px"/);
  assert.match(staticShell, /grid-template-columns:1\.05fr \.95fr;gap:56px/);
  assert.match(staticShell, /style="display:flex;align-items:center;gap:36px;padding:20px 24px;overflow:hidden"/);
  assert.match(staticShell, /Trusted by candidates targeting roles at/);
  assert.match(staticShell, /landing-company-ticker/);
  assert.match(staticShell, /landing-company-track/);
  assert.match(staticShell, /landing-company-segment/);
  assert.match(staticShell, /style="padding-top:96px;padding-bottom:64px"/);
  assert.match(staticShell, /style="max-width:720px;margin-bottom:56px"/);
  assert.match(staticShell, /style="padding-top:32px;padding-bottom:64px"/);
  assert.match(staticShell, /style="padding-top:64px;padding-bottom:96px"/);
  assert.match(staticShell, /style="border-radius:18px;padding:56px 48px/);
  assert.match(staticShell, /style="display:flex;align-items:center;gap:16px;padding:28px 24px;flex-wrap:wrap"/);
  assert.match(landingSource, /Resu<span className="serif italic font-normal">Me<\/span>/);
  assert.match(landingSource, /The resume tool|HOME_SEO_TITLE/);
  assert.match(landingSource, /ATS Grade/);
  assert.match(landingSource, /scorebar/);
  assert.match(landingSource, /aspectRatio:\s*"1\.05"/);
  assert.match(seoSource, /aspect-ratio:1\.05/);
  assert.match(landingSource, /Unlimited AI Resume Builder|HOME_SEO_TITLE/);
  assert.match(landingSource, /Start building now/);
  assert.match(landingSource, /Grade my resume/);
  assert.match(landingSource, /with ATS grading/);
  assert.match(source, /ResuMe by Ayush/);
  assert.doesNotMatch(landingSource, /built with care/);
  assert.doesNotMatch(staticShell, /built with care/);
  assert.match(staticShell, /ResuMe by Ayush · <a href="https:\/\/Ayuslh\.in"/);
  assert.match(staticShell, /<footer style="border-top:1px solid var\(--border\)">[\s\S]*<a href="\/" class="flex items-center gap-2">/);
  assert.match(landingSource, /src="\/favicon\.svg"/);
  assert.match(sidebarSource, /src="\/favicon\.svg"/);
  assert.match(staticShell, /<img src="\/favicon\.svg" alt="" aria-hidden="true"/);
  assert.doesNotMatch(landingSource, /<path d="M6 4h9l4 4v12H6z"/);
  assert.doesNotMatch(sidebarSource, /<FileText size=\{14\}/);
  assert.doesNotMatch(staticShell, /<path d="M6 4h9l4 4v12H6z"><\/path>/);
  assert.doesNotMatch(staticShell, />R<\/div>/);
  assert.doesNotMatch(landingSource, /landing-credit-item/);
  assert.doesNotMatch(staticShell, /landing-credit-item/);
  assert.match(landingSource, /src=\{template\.image\}/);
  assert.match(staticShell, /<img src="\/templates\/minimal\.png"/);
  assert.match(staticShell, /<img src="\/templates\/modern\.png"/);
  assert.match(staticShell, /<img src="\/templates\/professional\.png"/);
  assert.match(staticShell, /<img src="\/templates\/creative\.png"/);
  assert.doesNotMatch(staticShell, /id="seo" class="container pb-20"/);
  assert.match(staticShell, /class="sr-only" aria-label="ResuMe public search answers"/);
  assert.match(publicFooterSource, /href="https:\/\/Ayuslh\.in"/);
  assert.match(publicFooterSource, /target="_blank"/);
  assert.doesNotMatch(landingSource, /orb w-\[/);
  assert.doesNotMatch(landingSource, /landing-feature-panel/);
  assert.doesNotMatch(landingSource, /landing-credit-marquee/);
  assert.match(cssSource, /\.app-design\s*\{/);
  assert.match(cssSource, /\.app-design \.btn-lg\s*\{/);
  assert.match(cssSource, /\.app-design \.scorebar\s*\{/);
  assert.match(cssSource, /html\[data-route="\/"\][\s\S]*background:\s*#ffffff/);
  assert.match(cssSource, /html\[data-route="\/"\]\s+body[\s\S]*background-image:\s*none/);
  assert.doesNotMatch(landingSource, /\b(?:py-20|lg:py-24|pb-20|mb-12)\b/);
  assert.doesNotMatch(seoSource, /\b(?:py-20|lg:py-24|pb-20|mb-12)\b/);
  assert.match(source, /Audience fit/);
  assert.match(source, /Students, career switchers, and working professionals/);
  assert.match(source, /ATS methodology/);
  assert.match(source, /ResuMe looks at the target role, surfaces the keywords that matter/);
  assert.match(source, /Differentiation/);
  assert.match(source, /resume creation and resume grading in one flow/);
  assert.match(source, /Limitations/);
  assert.match(source, /No tool can promise interviews/);
  assert.match(source, /FAQ/);
  assert.match(source, /Can I start with a rough draft\?/);
  assert.match(source, /What does the grader look at\?/);
  assert.match(source, /Free AI Resume Builder/);
  assert.match(seoSource, /id="homepage-static-shell" class="app-design/);
  assert.match(indexSource, /HOMEPAGE_SEO_SHELL/);
  assert.doesNotMatch(source, /ATS-Friendly Resumes Built Faster with AI/);
  assert.doesNotMatch(source, /82 \/ 100/);
});
